from datetime import date, datetime, timedelta
from enum import Enum
from typing import Union

from pydantic import model_validator, BaseModel, Field, PositiveFloat, field_validator, ValidationInfo

from models.bom import BomLineRead
from models.process import PhaseParameters, StepWithMediaInfo
from models.product import ProductDoc
from commons.models.base_models import FlexModel, ArangoDocument
from commons.utils.dt import timestamp


class TimeDeltaInfo(FlexModel):
  absolute: timedelta | None = None
  relative: float | None = None

  # @validator('relative')
  # def above_minus_100percent(cls, v):
  #   if v <= -1:
  #     raise ValueError("Relative time delta must be above -100%")
  #   return v

class TargetActualTimeDelta(FlexModel):
  target: timedelta | None = None
  actual: timedelta | None = None
  delta: TimeDeltaInfo = TimeDeltaInfo()

# class TargetActualTime(FlexModel):
#   target: datetime | None = None
#   actual: datetime | None = None
#   delta: timedelta | None = None


class WorkStatus(str, Enum):
  CREATED = 'created'
  PLANNED = 'planned'
  STARTED = 'started'
  CLOSED = 'closed'


class WorkOrderNew(BaseModel):
  wo_code: str | None = None # Can be autogenerated
  product_key: str | None = None
  product_code: str | None = None
  product_description: str | None = None
  phase_sequence: list[str] = []
  qt_planned: PositiveFloat
  priority: bool = False
  project_code: str | None = None
  start_from: datetime | date | None = None
  due_by: datetime | date | None = None
  notes: str | None = None

  @model_validator(mode="before")
  @classmethod
  def check_key_or_code_provided(cls, values):
    if not values.get('product_key') and not values.get('product_code'):
      raise ValueError('A product key or code must be provided')
    return values



class WorkOrderFull(ArangoDocument, WorkOrderNew):
  status: WorkStatus = WorkStatus.CREATED
  qt_completed: float = 0
  active: bool = False
  on_time: bool = True
  critical: bool = False
  progress: int = Field(0, ge=0)

  created: datetime = Field(default_factory=timestamp)
  start: datetime | None = None
  end: datetime | None = None

  material_cost: float | None = None

  phase_sequence: list[str] = []
  wo_docs: list[ProductDoc] = []
  wo_bom: list[BomLineRead] = []


class RequiredAvailableQt(FlexModel):
  required: float | None = None
  available: float | None = None
  stockout: bool | None = None


class Operator(FlexModel):
  key: str = Field(..., alias="_key")
  name: str | None = None
  surname: str | None = None
  active: bool | None = None
  department_key: str | None = None


class Job(FlexModel):
  key: str | None = Field(None, alias="_key")
  wo_key: str
  wo_code: str
  phase_key: str
  phase_alias: str
  product_key: str
  product_code: str
  product_description: str
  operation_key: str
  project_code: str | None = None

  parameters: PhaseParameters | None = None

  first_phase: bool | None = None
  last_phase: bool | None = None

  stage: WorkStatus = WorkStatus.CREATED
  start_from: datetime | date | None = None
  due_by: datetime | date | None = None
  start: datetime | None = None
  active: bool = False
  critical: bool = False
  end: datetime | None = None

  qt_planned: float
  qt_completed: float = 0
  qt_released: float = 0

  step_sequence: list[StepWithMediaInfo] = []

  assigned_to: str | Operator | None = None

  issues_total: int | None = None
  issues_open: int | None = None

  progress: int = Field(0, ge=0)
  active_batch_key: str | None = None # batch _key
  active_batch_qt: int = 0
  next_batch_available: bool | None = None # WIP ONLY: This does not consider Production Items and subassemblies from other work orders

  # current_step: int | None = None

  on_time: bool = True
  estimated_remaining_time: timedelta | None = None
  estimated_completion: datetime | None = None

  last_work_session_started: str | None = None
  last_online: datetime | None = None

  job_docs: list[ProductDoc] = []
  job_bom: list[BomLineRead] = []

  forced: str | None = None

  notes: str | None = None
  # @validator('progress')
  # def between_0_and_100_percent(cls, v):
  #   if v < 0 or v > 1:
  #     raise ValueError("Progress must be between 0 and 100%")
  #   return v

  @field_validator('qt_released')
  def released_less_than_completed(cls, qt_released: float, info: ValidationInfo):
    if qt_released > info.data['qt_completed']:
      raise ValueError("Released quantity cannot exceed completed quantity")
    return qt_released

  # @validator('jobs_downstream', 'jobs_upstream', each_item=True)
  # def check_job_id_root(cls, job_id):
  #   if not job_id.startswith("Job/"):
  #     raise ValueError("Job id must be fully specified and must start with 'Job/'")
  #   return job_id


# class PhaseJobs(FlexModel):
#   phase_alias: str
#   active: bool
#   jobs: list[Job]

class JobUpdateType(str, Enum):
  INSERT = 'insert'
  UPDATE = 'update'
  CLOSE = 'close'


class JobUpdate(FlexModel):
  action: JobUpdateType
  data: dict

  # @validator('action')
  # def check_key_or_id(cls, action, values):
  #   # If action is delete or update, data must contain _id or _key field
  #   id_key = ['_id', '_key']
  #   print(cls, action, values)
  #   if action != JobUpdateType.INSERT and any([k in values['data'] for k in id_key]):
  #     raise ValueError("Job Update and Delete operations require Job key")
  #   return action




class WorkOrderDetails(WorkOrderFull):
  jobs: list[Job]


class OperatorAssignments(FlexModel):
  operator: Operator
  assigned_jobs: list[Job] | None = None
  independent: bool = False


class AssignmentsResponse(FlexModel):
  assigned_jobs_by_operator: list[OperatorAssignments] = []
  unassigned_jobs: list[Job] = []


class OperatorQueueUpdateInput(FlexModel):
  jobs: list[str] | None = None
  independent: bool | None = None


class QueueType(str, Enum):
  OPERATOR = 'o'
  EQUIPMENT = 'e'
  SITE = 's'


class Queue(ArangoDocument):
  type: QueueType #What the queue refers to
  site_key: str | None = None
  subqueue_target_key: str | None = None # id of operator / equipment
  work_orders: list[str] = [] # the list of Wo keys ordered by priority
  jobs: list[str] = [] # the list of job keys ordered by priority
  independent: bool = False # if true, the queue's sequence is will be independent from the main work order sequence
