services:
  - docker:dind

# Login to GitLab container Registry for push and pull operations
before_script:
  # - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD registry.gitlab.com

# Build Webapp image and push it to registry.
# Uses a multi-stage dockerfile with intermediate builder image to reduce final image size and build time
build:webapp:
  stage: build
  only:
    refs:
      - DEV
      - master
    changes:
      - webapps/main/**/*
  image: docker:latest
  variables:
    WEBAPP_ROOT: webapps/main
    WEBAPP_DOCKERFILE: webapp.prod.Dockerfile
    WEBAPP_IMAGE: $CI_REGISTRY_IMAGE/app
  tags:
    - docker
  script:
    # Pull builder image if present, if not skip
    - docker pull $WEBAPP_IMAGE:global-deps-stage || true
    - docker pull $WEBAPP_IMAGE:develop-stage || true
    - docker pull $WEBAPP_IMAGE:config-stage || true
    - docker pull $WEBAPP_IMAGE:build-stage || true

    # Navigate to build context
    - cd $WEBAPP_ROOT

    # Build global-deps image (first section of the Dockerfile), using cached layers when available. The tagging overwrites the image with the updated one
    - >
      docker build
      --pull
      --cache-from $WEBAPP_IMAGE:global-deps-stage
      --target global-deps-stage
      -t $WEBAPP_IMAGE:global-deps-stage
      -f $WEBAPP_DOCKERFILE
      .

    # develop-stage
    - >
      docker build
      --pull
      --cache-from $WEBAPP_IMAGE:sdevelop-stage
      --target develop-stage
      -t $WEBAPP_IMAGE:develop-stage
      -f $WEBAPP_DOCKERFILE
      .

    # config-stage
    - >
      docker build
      --pull
      --cache-from $WEBAPP_IMAGE:config-stage
      --target config-stage
      -t $WEBAPP_IMAGE:config-stage
      -f $WEBAPP_DOCKERFILE
      .

    # build-stage
    - >
      docker build
      --pull
      --cache-from $WEBAPP_IMAGE:build-stage
      --target build-stage
      -t $WEBAPP_IMAGE:build-stage
      -f $WEBAPP_DOCKERFILE
      .

    # Build the final image using cached layers from each stage's image. Tag the image with current pipeline ID and `latest` tag.
    - >
      docker build
      --pull
      --cache-from $WEBAPP_IMAGE:global-deps-stage
      --cache-from $WEBAPP_IMAGE:develop-stage
      --cache-from $WEBAPP_IMAGE:config-stage
      --cache-from $$WEBAPP_IMAGE:latest
      -t $WEBAPP_IMAGE:latest
      -t $WEBAPP_IMAGE:$CI_PIPELINE_ID
      -f $WEBAPP_DOCKERFILE
      .

    # Push new images to the registry
    - docker push $WEBAPP_IMAGE:global-deps-stage
    - docker push $WEBAPP_IMAGE:develop-stage
    - docker push $WEBAPP_IMAGE:config-stage
    - docker push $WEBAPP_IMAGE:latest
    - docker push $WEBAPP_IMAGE:$CI_PIPELINE_ID


build:api:
  stage: build
  only:
    refs:
      - master
      - DEV
    changes:
      - backend/api/**/*
  image: docker:latest
  variables:
    API_ROOT: backend/api
    API_DOCKERFILE: Dockerfile
    API_IMAGE: $CI_REGISTRY_IMAGE/api
  tags:
    - docker
  script:
    # Navigate to build context
    - cd $API_ROOT

    # Build image using cache from existing ones
    - >
      docker build
      --pull
      --cache-from $API_IMAGE:latest
      -t $API_IMAGE:$CI_PIPELINE_ID
      -t $API_IMAGE:latest
      -f $API_DOCKERFILE
      .

    # Push new images to the registry
    - docker push $API_IMAGE:latest
    - docker push $API_IMAGE:$CI_PIPELINE_ID

