*** Variables ***
${api_username}         simone
${api_password}         simone

${no_token_defined}     no token defined


${workorder_product_key}    14190259
${workorder_create_quantity}    100
${workorder_new_batch_quantity}    5

${movement_product_key}    12221058
${movement_position_to}    30199840
${movement_position_from}    OUT
${movement_status}    completed
${movement_type}    receipt
