---
- name: Init DB
  hosts: all
  vars:
    root_dir: /opt/progress
    data_init_file: db_data_init.py

  tasks:

    - name: Create project directory
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      loop:
        - "{{ root_dir }}"
        - "{{ root_dir }}/db_backup"
        - "{{ root_dir }}/media"
        - "{{ root_dir }}/logs"

    - name: Create DB data persistence volume
      community.docker.docker_volume:
        name: db_data
        recreate: always

    - name: Create DB backup volume
      community.docker.docker_volume:
        name: db_backup
        driver_options:
          o: bind
          type: none
          device: /opt/progress/db_backup

    - name: Create Media files volume
      community.docker.docker_volume:
        name: db_backup
        driver_options:
          o: bind
          type: none
          device: /opt/progress/media

    - name: Create log files volume
      community.docker.docker_volume:
        name: db_backup
        driver_options:
          o: bind
          type: none
          device: /opt/progress/logs

    - name: Run temporary DB container to bootstrap data volume
      community.docker.docker_container:
        name: temp-db
        image: arangodb:3.7
        recreate: yes
        state: started
        auto_remove: yes
        ports:
          - 8529:8529
        volumes:
          - db_data:/var/lib/arangodb3:rw
        env:
          ARANGO_NO_AUTH: "1"

    - name: Copy init script
      ansible.builtin.copy:
        src: db_data_init.py
        dest: "{{ root_dir }}/{{ data_init_file }}"

    - name: Run setup script
      ansible.builtin.shell:
        chdir: "{{ root_dir }}"
        cmd: "python3 {{ data_init_file }}"

    - name: Remove setup script
      ansible.builtin.command:
        chdir: "{{ root_dir }}"
        cmd: rm {{ data_init_file }}


