---
- name: Install docker and python requirements
  hosts: all
  become: true
  tags: requirements

  tasks:
    - name: Install aptitude
      apt:
        name: aptitude
        state: latest
        update_cache: true

    - name: Install required system packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: latest
        update_cache: true

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Update apt and install docker-ce
      apt:
        name: docker-ce
        state: latest
        update_cache: true

    - name: Install docker and arangodb sdk for python
      pip:
        name:
          - docker
          - python-arango


- name: Setup app directories and docker volumes
  hosts: all
  become: true
  tags: volumes

  vars:
    root_dir: /opt/progress

  tasks:
    - name: Create project directory
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      loop:
        - "{{ root_dir }}"
        - "{{ root_dir }}/db_backup"
        - "{{ root_dir }}/media"
        - "{{ root_dir }}/logs"

    - name: Create DB data persistence volume
      community.docker.docker_volume:
        name: db_data
        recreate: always

    - name: Create DB backup volume
      community.docker.docker_volume:
        name: db_backup
        driver_options:
          o: bind
          type: none
          device: /opt/progress/db_backup

    - name: Create Media files volume
      community.docker.docker_volume:
        name: media
        driver_options:
          o: bind
          type: none
          device: /opt/progress/media

    - name: Create log files volume
      community.docker.docker_volume:
        name: logs
        driver_options:
          o: bind
          type: none
          device: /opt/progress/logs

- name: Init swarm and secrets
  hosts: all
  become: true
  tags: secrets
  vars:
    swarm_join_tkn_manager: '{{ init.swarm_facts.JoinTokens.Manager }}'
    swarm_join_tkn_worker: '{{ init_data.swarm_facts.JoinTokens.Worker }}'

  tasks:

    - name: Activate Swarm mode
      community.docker.docker_swarm:
        state: present
      register: init

    
# - name: Start dummy DB service for data initialization
#   hosts: all
#   become: True

#   tasks:

