version: '3.1'

volumes:
  media:
    external: True
  db_backup:
    external: True
  db_data:
    external: True

services:

  router:
    image: traefik:v2.3
    restart: unless-stopped
    deploy:
      replicas: 1
    volumes:
      # So that Traefik can listen to the Docker events
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik/traefik.toml:/etc/traefik/traefik.toml"
    ports:
      # The HTTP port
      - "80:80"
      # The HTTPS post
      - "443:443"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"

  api:
    environment:
      - PROGRESS_MEDIA_PATH=/media
      - PROGRESS_ARANGO_URL=http://db:8529
      - PROGRESS_API_ROOT_PATH=/api
    ports:
      - "8000"
    volumes:
      - media:/media

  db:
    image: arangodb:3.7
    volumes:
      - db_data:/var/lib/arangodb3
      - db_backup:/db_backup
    ports:
      - "8529"


