services:

  # ========== ROUTER / REVERSE-PROXY ==========
  router:
    image: traefik:v2.3
    restart: unless-stopped
    volumes:
      # So that Traefik can listen to the Docker events
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik/traefik.toml:/etc/traefik/traefik.toml"
    ports:
      # The HTTP port
      - "80:80"
      # The HTTPS post
      - "443:443"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"

  # ========== UI ==========
  app:
    restart: unless-stopped
    labels:
      - traefik.http.routers.app.rule=Host(`progress.localhost`)

  # ========== API ==========
  api:
    restart: unless-stopped
    depends_on:
      - db
    environment:
      # Here the service will be called from INSIDE the docker network, so the internal alias should be used.
      - PROGRESS_ARANGO_URL=http://db:8529
      - PROGRESS_ROOT_PATH=/api
    ports:
      - "8000"
    labels:
      - "traefik.http.routers.api.rule=Host(`progress.localhost`) && PathPrefix(`/api`)"
      - "traefik.http.middlewares.strip_api_prefix.stripprefix.prefixes=/api"
      - "traefik.http.middlewares.strip_api_prefix.stripprefix.forceslash=false"
      - "traefik.http.middlewares.root_to_docs.replacepathregex.regex=^/?$$"
      - "traefik.http.middlewares.root_to_docs.replacepathregex.replacement=/docs"
      - "traefik.http.routers.api.middlewares=strip_api_prefix, root_to_docs"


  # ========== DB ==========
  db:
    image: arangodb:3.7
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/arangodb3
    ports:
      - "8529"
    labels:
      - "traefik.http.routers.db.rule=Host(`progress.localhost`) && PathPrefix(`/_db`)"
      - "traefik.http.middlewares.db_root.replacepathregex.regex=^/_db/?$$"
      - "traefik.http.middlewares.db_root.replacepathregex.replacement=/"
      - "traefik.http.routers.db.middlewares=db_root"

      # - "traefik.http.routers.db.middlewares=strip_db_prefix"
      # - "traefik.http.middlewares.strip_db_prefix.stripprefix.prefixes=/_db"
      # - "traefik.http.middlewares.strip_db_prefix.stripprefix.forceslash=false"


