version: '3'

volumes:
  db_data:
    external:
      name: arango-persist


services:

  dev-app:
    build:
      context: ./webapps/main
      dockerfile: webapp.dev.Dockerfile
    restart: unless-stopped
    command: >
      npm run serve -- --host 0.0.0.0
    volumes:
      # This is use to keep HMR working
      - "./webapps/main/public:/main/public"
      - "media:/main/public/media"
      - "./webapps/main/src:/main/src"
    environment:
      # the app will call the api server from outside the docker network, so the full Traefik host alias should be used
      - VUE_APP_API_BASE_URL=http://progress.localhost/api
      - VUE_APP_I18N_LOCALE=it
      - VUE_APP_I18N_FALLBACK_LOCALE=it
      # - DEBUG=express:*
    ports:
      - "8080"
    labels:
      - traefik.http.routers.app.rule=Host(`progress.localhost`)

  api:
    build:
      context: ./backend/api #root folder for build
    volumes:
      - ./backend/api:/api
    command: >
      uvicorn main:app --host 0.0.0.0 --reload --log-level debug --use-colors


  db:
    volumes:
      - ./db/arango.conf:/etc/arangodb3/arangod.conf
    environment:
      - ARANGO_NO_AUTH=1
