version: '3.1'

secrets:
  db_pwd_progress_api:
    external: True
  jwt_token_secret:
    external: True

services:

  prod-app:
    image: registry.gitlab.com/progresslab/progress-platform/app
    deploy:
      replicas: 1
      labels:
        - "traefik.http.routers.api.rule=Host(`progress.localhost`) && PathPrefix(`/api`)"
        - "traefik.http.middlewares.strip_api_prefix.stripprefix.prefixes=/api"
        - "traefik.http.middlewares.strip_api_prefix.stripprefix.forceslash=false"
        - "traefik.http.routers.api.middlewares=strip_api_prefix"
    volumes:
      - media:/usr/share/nginx/html/media
    ports:
      - "80"

  api:
    image: registry.gitlab.com/progresslab/progress-platform/api
    deploy:
      replicas: 1
      labels:
        - "traefik.http.routers.api.rule=Host(`progress.localhost`) && PathPrefix(`/api`)"
        - "traefik.http.middlewares.strip_api_prefix.stripprefix.prefixes=/api"
        - "traefik.http.middlewares.strip_api_prefix.stripprefix.forceslash=false"
        - "traefik.http.routers.api.middlewares=strip_api_prefix"
    secrets:
      - source: db_pwd_progress_api
        target: api_db_pwd
      - source: jwt_token_secret
    volumes:
      - media:/media
    environment:
      - PROGRESS_API_DB_USERNAME=progress_api
      - PROGRESS_API_DB_PWD_FILE=/run/secrets/api_db_pwd
      - PROGRESS_JWT_TOKEN_SECRET_FILE=/run/secrets/jwt_token_secret
    command:
      ["gunicorn", "-k", "uvicorn.workers.UvicornWorker", "-b", "0.0.0.0", "--access-logfile", "-", "main:app"]
