version: '3'

services:

  app:
    # this is an NGINX image with built vue files embedded
    image: registry.gitlab.com/progresslab/progress-platform/app
    restart: unless-stopped
    volumes:
      - ./webapps/main/public/media:/usr/share/nginx/html/media
    ports:
      - "80"

  api:
    image: registry.gitlab.com/progresslab/progress-platform/api
    command:
      ["gunicorn", "-k", "uvicorn.workers.UvicornWorker", "-b", "0.0.0.0", "--access-logfile", "-", "main:app"]

  db:
    volumes:
      - /etc/progress/db_backup:/db_backup
      # - ./db/arango.conf:/etc/arangodb3/arangod.conf
    environment:
      # TODO: Change to setup root password
      - ARANGO_NO_AUTH=1
