version: '3'

volumes:
  db_data:
    external:
      name: arango-persist


services:

  prod-app:
    # this is an NGINX image with built vue files embedded
    build:
      context: webapps/main
      dockerfile: webapp.prod.Dockerfile
    volumes:
      - media:/usr/share/nginx/html/media
      - ./webapps/main/nginx.prod.conf:/etc/nginx/nginx.conf
    ports:
      - "80"
    labels:
      - traefik.http.routers.app.rule=Host(`progress.localhost`)

  api:
    build:
      context: ./backend/api #root folder for build
    volumes:
      - ./backend/api:/api
    command:
      ["gunicorn", "-k", "uvicorn.workers.UvicornWorker", "-b", "0.0.0.0", "--access-logfile", "-", "main:app", "--reload"]

  db:
    volumes:
      - ./db/arango.conf:/etc/arangodb3/arangod.conf
    environment:
      - ARANGO_NO_AUTH=1
