---
# Environment variables for Progress Platform
DNS_PROVIDER: godaddy
DNS_API_KEY_VAR: GODADDY_API_KEY
DNS_API_SECRET_VAR: GODADDY_API_SECRET
DOMAIN: progresslab.it
SUBDOMAIN: test
DNS_DELAY: 60
VERSION: 0.10.a3
DNS_EMAIL: admin@progresslab.it
DNS_API_KEY: e4XtbHbJViD9_DSurGuwinHJ4XduTykCTj
DNS_API_SECRET: Ky26ZY9New6EpUy6FGsNJJ




