---
# Environment variables for Progress Platform
DOMAIN: progresslab.it
SUBDOMAIN: testhttps
VERSION: 0.10.b4

#DNS_PROVIDER: godaddy
#DNS_API_KEY_VAR: GODADDY_API_KEY
#DNS_API_SECRET_VAR: GODADDY_API_SECRET
#DNS_DELAY: 60
#DNS_EMAIL: admin@progresslab.it
#DNS_API_KEY: e4XtbHbJViD9_DSurGuwinHJ4XduTykCTj
#DNS_API_SECRET: Ky26ZY9New6EpUy6FGsNJJ




