
networks:
  progress:
    name: progress

secrets:
  progress_admin_pwd:
    file: ../secrets/dev/admin_pwd.txt
  progress_api_db_pwd:
    file: ../secrets/dev/api_db_pwd.txt
  progress_jwt_secret:
    file: ../secrets/dev/jwt_secret.txt
  progress_db_root_pwd:
    file: ../secrets/dev/db_root_pwd.txt

services:
  router:
    restart: unless-stopped
    networks:
      - progress
    command:
      - --providers.docker
      - --accesslog
      - --api.dashboard
      - --api.debug
      - --api.insecure
      - --log.level=INFO

  api:
    restart: unless-stopped
    networks:
      - progress
    build:
      context: ../../backend/api
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "3"
    volumes:
      - ../../backend/api:/api
    environment:
      - PROGRESS_DB_NAME=PROGRESS_PROD
      - PROGRESS_WEBAPP_URL=http://localhost:9000
      - PREFECT_API_URL=${PREFECT_API_URL:-http://host.docker.internal:4200/api}
    command:
      - "sh"
      - "-c"
      - |
        pip install -r /api/requirements.txt \
        && pip install debugpy -t /tmp \
        && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 \
        -m uvicorn main:app --host 0.0.0.0 --port 8000 --reload --log-level debug --use-colors --timeout-graceful-shutdown 5
    ports:
      - 8000:8000
      - 5678:5678
    labels:
      - "traefik.http.routers.api.rule=Host(`${PROGRESS_ADDRESS:-progress.localhost}`) && PathPrefix(`/api`)"
      - "traefik.http.middlewares.strip_api_prefix.stripprefix.prefixes=/api"
      - "traefik.http.middlewares.strip_api_prefix.stripprefix.forceslash=false"
      - "traefik.http.routers.api.middlewares=strip_api_prefix"

  db:
    image: arangodb:3.11
    restart: unless-stopped
    networks:
      - progress
    environment:
      - ARANGO_NO_AUTH=1
    ports:
      - 8529:8529
    labels:
      - "traefik.http.routers.db.rule=Host(`${PROGRESS_ADDRESS:-progress.localhost}`) && PathPrefix(`/_db`)"
      - "traefik.http.middlewares.db_root.replacepathregex.regex=^/_db/?$$"
      - "traefik.http.middlewares.db_root.replacepathregex.replacement=/"
      - "traefik.http.routers.db.middlewares=db_root"

  broker:
    image: nats:2-alpine
    hostname: broker
    restart: unless-stopped
    networks:
      - progress
    command: ["-c", "/etc/nats/nats-server.conf"]
    volumes:
      - nats_data:/data
      - ../config/nats-server.conf:/etc/nats/nats-server.conf:ro
    ports:
      - "4222:4222"
      - "8222:8222"
      - "1883:1883"
