volumes:
  robot_reports:
    external: True

services:
  router:
    restart: unless-stopped
    command:
      - --providers.docker
      - --accesslog
      - --api.dashboard
      - --api.debug
      - --api.insecure
      - --log.level=INFO

  # app:
  #   restart: unless-stopped
  #   build:
  #     context: ./webapps/quasar
  #     dockerfile: webapp.dev.Dockerfile
  #   restart: unless-stopped
  #   labels:
  #     - traefik.http.routers.app.rule=Host(`${PROGRESS_ADDRESS:-progress.localhost}`)
  #     - traefik.http.routers.hmr.rule=Host(`${PROGRESS_ADDRESS:-progress.localhost:9000}`)
  #   command: yarn quasar dev --host 0.0.0.0
  #   volumes:
  #     # This is use to keep HMR working
  #     - "./webapps/quasar:/app"
  #     - /app/node_modules/ # exclude local node_modules folder from being linked into the container
  #     - "media:/app/public/media"
  #   environment:
  #     # the app will call the api server from outside the docker network, so the full Traefik host alias should be used
  #     - VUE_APP_API_BASE_URL=${PROGRESS_ADDRESS:-progress.localhost}/api
  #     - VUE_APP_I18N_LOCALE=it
  #     - VUE_APP_I18N_FALLBACK_LOCALE=it
  #   ports:
  #     - "9000"

  api:
    restart: unless-stopped
    build:
      context: ./backend/api #root folder for build
    volumes:
      - ./backend/api:/api
      - ./backend/commons:/api/commons
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "3"
    environment:
      - PROGRESS_DB_NAME=PROGRESS_PROD
      - PROGRESS_WEBAPP_URL=http://localhost:9000
      - PREFECT_API_URL=${PREFECT_API_URL:-http://host.docker.internal:4200/api}
    command:
      - "sh"
      - "-c"
      - |
        pip install -r /api/requirements.txt \
        && pip install debugpy -t /tmp \
        && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 \
        -m uvicorn main:app --host 0.0.0.0 --port 8000 --reload --log-level debug --use-colors --timeout-graceful-shutdown 1
    ports:
      - 8000:8000
      - 5678:5678
    labels:
      - "traefik.http.routers.api.rule=Host(`${PROGRESS_ADDRESS:-progress.localhost}`) && PathPrefix(`/api`)"
      - "traefik.http.middlewares.strip_api_prefix.stripprefix.prefixes=/api"
      - "traefik.http.middlewares.strip_api_prefix.stripprefix.forceslash=false"
      - "traefik.http.routers.api.middlewares=strip_api_prefix"

  # robot:
  #   restart: unless-stopped
  #   build:
  #     context: ./testing/robot-test #root folder for build
  #   volumes:
  #     - ./testing/robot-test/data:/robot-framework/data
  #     - ./testing/robot-test/resources:/robot-framework/resources
  #     - ./testing/robot-test/tests:/robot-framework/tests
  #     - robot_reports:/robot-framework/reports
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "1k"
  #       max-file: "3"
  #   environment:
  #     - PROGRESS_DB_NAME=PROGRESS_PROD
  #     - PROGRESS_ARANGO_URL=http://db:8529
  #   #ports:
  #   #  - 6612:6612
  #   #command: >
  #   #  robot --outputdir reports tests
  #   command:
  #     - "sh"
  #     - "-c"
  #     - |
  #       pip install debugpy -t /tmp \
  #       && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5680 \
  #       -m robot --outputdir reports tests
  #   ports:
  #     - 5680:5680

  #traceability-service:
  #  restart: unless-stopped
  #  build:
  #    context: ./backend/traceability-service #root folder for build
  #  volumes:
  #    - ./backend/traceability-service:/traceability-service
  #    - ./backend/commons:/traceability-service/commons
  #  environment:
  #    - PROGRESS_DB_NAME=PROGRESS_PROD
  #  command:
  #    - "sh"
  #    - "-c"
  #    - |
  #      pip install debugpy -t /tmp \
  #      && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5778 \
  #      -m uvicorn main:app --host 0.0.0.0 --port 8100 --reload --log-level debug --use-colors  --timeout-graceful-shutdown 1
  #  ports:
  #    - 8100:8100
  #    - 5778:5778
  #  labels:
  #    - "traefik.http.routers.api.rule=Host(`${PROGRESS_ADDRESS:-progress.localhost}`) && PathPrefix(`/traceability-service`)"
  #    - "traefik.http.middlewares.strip_api_prefix.stripprefix.prefixes=/traceability-service"
  #    - "traefik.http.middlewares.strip_api_prefix.stripprefix.forceslash=false"
  #    - "traefik.http.routers.api.middlewares=strip_api_prefix"

  db:
    image: arangodb:3.11 # Use this for Intel Processors
    #image: arm64v8/arangodb:3.11 # This works for Apple Silicon M1-M3 processors
    restart: unless-stopped
    environment:
      - ARANGO_NO_AUTH=1
    ports:
      - 8529:8529
    labels:
      - "traefik.http.routers.db.rule=Host(`${PROGRESS_ADDRESS:-progress.localhost}`) && PathPrefix(`/_db`)"
      - "traefik.http.middlewares.db_root.replacepathregex.regex=^/_db/?$$"
      - "traefik.http.middlewares.db_root.replacepathregex.replacement=/"
      - "traefik.http.routers.db.middlewares=db_root"
