volumes:
  workflow_db:
    external: true
  workflow_config:
    external: true
  flows:
    external: true
  cmounts:
    external: true

networks:
  progress:
    external: true

secrets:
  progress_api_db_pwd:
    external: true

services:
  wf-integration-agent: # Client Workflow Agent
    image: prefecthq/prefect:3-latest
    entrypoint: >
      sh -c "chmod +x /flows/entrypoint.sh &&
             /usr/bin/tini -g -- /flows/entrypoint.sh"
    depends_on:
      - wf-server
    volumes:
      - flows:/flows
      - cmounts:/cmounts
    networks:
      - progress
    secrets:
      - progress_api_db_pwd
    environment:
      - PREFECT_API_URL=http://wf-server:4200/workflow/api
    deploy:
      replicas: 1
