volumes:
  cmounts:
    external: true
  media:
    external: true
  notebooks:
    external: true

networks:
  progress:
    external: true

secrets:
  progress_api_db_pwd:
    external: true

services:
  notebooks: # Jupyter lab
    image: quay.io/jupyter/base-notebook
    volumes:
      - media:/media
      - cmounts:/cmounts
      - notebooks:/home/jovyan/work
    networks:
      - progress
    secrets:
      - progress_api_db_pwd
    command: |
      start-notebook.py
      --ServerApp.ip='*'
      --ServerApp.port=8888
      --ServerApp.base_url=/notebooks/
      --ServerApp.allow_root=True
      --ServerApp.open_browser=False
      --ServerApp.allow_remote_access=True
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=progress"
        - "traefik.http.services.notebooks.loadbalancer.server.port=8888"
        - "traefik.http.routers.notebooks.entrypoints=websecure"
        - "traefik.http.routers.notebooks.rule=Host(`${SUBDOMAIN}.${DOMAIN:-progresslab.it}`) && PathPrefix(`/notebooks`)"
        - "traefik.http.routers.notebooks.priority=10"
        - "traefik.http.routers.notebooks.tls.certresolver=letsencrypt"
