networks:
  progress:
    external: true

secrets:
  print_service_pwd:
    file: /opt/progress/config/.print_service_pwd

services:
  print-service:
    image: registry.gitlab.com/progresslab/progress-platform/print-service:${VERSION}
    restart: unless-stopped
    networks:
      - progress
    environment:
      PROGRESS_PRINT_SERVICE_API_URL: http://api:8000/api
    secrets:
      - source: print_service_pwd
        target: progress_print_service_api_password
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=false"
