networks:
  progress:
    external: true

services:
  print-service:
    image: registry.gitlab.com/progresslab/progress-platform/print-service:${VERSION}
    restart: unless-stopped
    networks:
      - progress
    environment:
      PROGRESS_PRINT_SERVICE_NATS_URL: nats://broker:4222
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=false"
