version: "3.9"

volumes:
  reports:
    external: true
  cmounts:
    external: true

networks:
  progress:
    external: true

secrets:
  progress_api_db_pwd:
    external: true

services:
  reporting: # Streamlit app
    image: python:3.11-slim
    restart: unless-stopped
    volumes:
      - reports:/app
      - cmounts:/cmounts
    networks:
      - progress
    ports:
      - "8501:8501"
    secrets:
      - progress_api_db_pwd
    entrypoint: >
      sh -c "chmod +x /app/entrypoint.sh && /app/entrypoint.sh"
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=progress"
        - "traefik.http.services.reporting.loadbalancer.server.port=8501"
        - "traefik.http.routers.reporting.rule=HostRegexp(`{anyhost:.*}`) && PathPrefix(`/reports`)"
        - "traefik.http.routers.reporting.middlewares=strip_reporting_prefix"
        - "traefik.http.middlewares.strip_reporting_prefix.stripprefix.prefixes=/reports"
        - "traefik.http.middlewares.strip_reporting_prefix.stripprefix.forceslash=false"
