volumes:
  media:
    external: true

networks:
  progress:
    external: true

services:
  warehouse:
    image: registry.gitlab.com/progresslab/progress-platform/warehouse:${VERSION}
    volumes:
      - /opt/progress/config/appConfig.js:/usr/share/nginx/html/config.js
      - media:/usr/share/nginx/html/media
    depends_on:
      - api
    networks:
      - progress
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=progress"
        - "traefik.http.services.warehouse.loadbalancer.server.port=80"
        - "traefik.http.routers.warehouse.rule=Host(`${SUBDOMAIN}.${DOMAIN:-progresslab.it}`) && PathPrefix(`/wh`)"
        - "traefik.http.routers.warehouse.entrypoints=websecure"
        - "traefik.http.routers.warehouse.tls.certresolver=letsencrypt"
        - "traefik.http.routers.warehouse.middlewares=strip_warehouse_prefix"
        - "traefik.http.middlewares.strip_warehouse_prefix.stripprefix.prefixes=/wh"
