volumes:
  media:
    external: true
  config:
    external: true

networks:
  progress:
    external: true

services:
  warehouse:
    image: registry.gitlab.com/progresslab/progress-platform/warehouse:${VERSION}
    volumes:
      - type: volume
        source: config
        target: /usr/share/nginx/html/config.js
        volume:
          subpath: appConfig.js
        read_only: true
      - media:/usr/share/nginx/html/media
    depends_on:
      - api
    networks:
      - progress
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=progress"
        - "traefik.http.services.warehouse.loadbalancer.server.port=80"
        - "traefik.http.routers.warehouse.rule=Host(`${HOST}`) && PathPrefix(`/wh`)"
        - "traefik.http.routers.warehouse.middlewares=strip_warehouse_prefix"
        - "traefik.http.middlewares.strip_warehouse_prefix.stripprefix.prefixes=/wh"
