volumes:
  workflow_db:
    external: true
  workflow_config:
    external: true
  flows:
    external: true

secrets:
  progress_api_db_pwd:
    external: true

networks:
  progress:
    external: true

services:
  wf-server: # Workflow Server
    image: prefecthq/prefect:2-python3.11
    restart: always
    depends_on:
      - workflow_db
    volumes:
      - workflow_config:/root/.prefect
    entrypoint: ["prefect", "server", "start"]
    networks:
      - progress
    environment:
      PREFECT_SERVER_API_HOST: 0.0.0.0
      PREFECT_API_DATABASE_CONNECTION_URL: postgresql+asyncpg://postgres:postgres@workflow-db:5432/prefect
      PREFECT_UI_API_URL: https://${SUBDOMAIN}.${DOMAIN}/wf/api
      PREFECT_UI_URL: https://${SUBDOMAIN}.${DOMAIN}/wf
      PREFECT_UI_SERVE_BASE: /wf
    deploy:
      replicas: 1
      labels:
        # Main config
        - "traefik.enable=true"
        - "traefik.docker.network=progress"
        - "traefik.http.services.wf-server.loadbalancer.server.port=4200"
        # Routing
        - "traefik.http.routers.wf-server.rule=Host(`${SUBDOMAIN}.${DOMAIN}`) && PathPrefix(`/wf`)"
        - "traefik.http.routers.wf-server.service=wf-server"
        # TLS
        - "traefik.http.routers.wf-server.entrypoints=websecure"
        - "traefik.http.routers.wf-server.tls.certresolver=letsencrypt"

  wf-system-agent: # System Workflow Agent
    image: registry.gitlab.com/progresslab/progress-platform/wf-sys-agent:${VERSION}
    restart: always
    depends_on:
      - wf-server
    networks:
      - progress
    secrets:
      - progress_api_db_pwd
    environment:
      - PREFECT_API_URL=http://wf-server:4200/api
    deploy:
      replicas: 1

  workflow-db:
    image: postgres:15.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=prefect
    networks:
      - progress
    expose:
      - 5432:5432
    volumes:
      - workflow_db:/var/lib/postgresql/data
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=progress"
        - "traefik.http.services.workflow-db.loadbalancer.server.port=5432"
