[server]
authentication = false
statistics = false

[rocksdb]
max-total-wal-size = 1024000
write-buffer-size = 2048000
max-write-buffer-number = 2
total-write-buffer-size = 81920000
dynamic-level-bytes = false
block-cache-size = 2560000
enforce-block-cache-size-limit = true

[cache]
size = 10485760

[javascript]
v8-contexts = 2
v8-max-heap = 512

