from datetime import datetime
from enum import Enum
from typing import Any, Literal


from pydantic import Field, model_validator, BaseModel

from models.base_models import ArangoDocument
from utils.dt import timestamp
from utils.search import WildcardString
from utils.dt import timestamp



# ========================================================
# STOCK COUNTING
# ========================================================

class InventoryCountSessionStatus(str, Enum):
  PLANNED = 'planned'
  STARTED = 'started'
  COMPLETED = 'completed'
  PROCESSING = 'processing'
  APPLIED = 'applied'
  CANCELED = 'canceled'

class InventoryCountSessionType(str, Enum):
  BY_POSITION = 'position'
  BY_PRODUCT = 'product'

class InventoryCountSession(ArangoDocument):
  code: str | None = Field(None, description="Auto-generated session code (e.g. from a counter) if not provided by the user.", examples=["CNT-2026-001"])
  description: str | None = Field(None, description="Human-readable description of the counting session scope.", examples=["Annual full-warehouse count Q2 2026"])
  type: InventoryCountSessionType = Field(..., description="Counting dimension: `position` (count by storage location) or `product` (count by product).", examples=["position"])
  status: InventoryCountSessionStatus = Field(InventoryCountSessionStatus.PLANNED, description="Current lifecycle status of the session.", examples=["planned"])
  blind_quantities: bool = Field(True, description="If True, expected quantities are hidden from operators during counting.", examples=[True])
  blind_serials: bool = Field(True, description="If True, expected serial numbers are hidden from operators during counting.", examples=[True])
  coverage_percentage: float | None = Field(None, description="Calculated field: percentage of inventory items covered by this session's assignments.", examples=[100.0])

  # Schedule
  scheduled_start: datetime | None = Field(None, description="Planned start datetime for the counting session.", examples=["2026-05-20T08:00:00Z"])
  scheduled_end: datetime | None = Field(None, description="Planned end datetime for the counting session.", examples=["2026-05-20T18:00:00Z"])

  # Audit trail
  created: datetime = Field(default_factory=timestamp, description="Timestamp when the session was created.", examples=["2026-05-15T10:00:00Z"])
  created_by: str | None = Field(None, description="User key of the operator who created the session.", examples=["user/operator-01"])
  started: datetime | None = Field(None, description="Timestamp when the first assignment was started.", examples=["2026-05-20T08:05:00Z"])
  completed: datetime | None = Field(None, description="Timestamp when the session was marked as completed (all assignments done).", examples=["2026-05-20T17:45:00Z"])

  baseline_snapshot_key: str | None = Field(None, description="Key of the `InventorySnapshot` capturing the pre-count inventory state.", examples=["snap-001"])
  post_count_snapshot_key: str | None = Field(None, description="Key of the `InventorySnapshot` capturing the post-count inventory state.", examples=["snap-002"])
  post_adjustment_snapshot_key: str | None = Field(None, description="Key of the `InventorySnapshot` capturing inventory state after adjustments were applied.", examples=["snap-003"])
  adjustment_list_key: str | None = Field(None, description="Key of the `MovementList` generated by the count application to reconcile discrepancies.", examples=["mvtlist-001"])

  # Metadata
  notes: str | None = Field(None, description="Free-text notes for the counting session.", examples=["Verify all rows in zone A before zone B"])
  extra: Any = Field(None, description="Arbitrary extra metadata.", examples=[None])

class InventoryCountAssignmentStatus(str, Enum):
  PLANNED = 'planned'
  STARTED = 'started'
  COMPLETED = 'completed'
  CANCELED = 'canceled'


class InventoryCountSessionUpdate(BaseModel):
  code: str | None = Field(None, description="New session code (only editable while in `planned` status).", examples=["CNT-2026-002"])
  description: str | None = Field(None, description="Updated description.", examples=["Updated scope: zones A and B only"])
  type: InventoryCountSessionType | None = Field(None, description="Counting dimension (only editable while in `planned` status).", examples=["position"])
  blind_quantities: bool | None = Field(None, description="Updated blind quantities setting (only editable while in `planned` status).", examples=[False])
  blind_serials: bool | None = Field(None, description="Updated blind serials setting (only editable while in `planned` status).", examples=[False])
  scheduled_start: datetime | None = Field(None, description="Updated scheduled start (only editable while in `planned` status).", examples=["2026-05-21T08:00:00Z"])
  scheduled_end: datetime | None = Field(None, description="Updated scheduled end.", examples=["2026-05-21T18:00:00Z"])
  notes: str | None = Field(None, description="Updated notes.", examples=["Prioritise zone A"])

class InventoryCountSessionSearchParams(BaseModel):
  search: WildcardString = Field(None, description="Wildcard search on session code.", examples=["CNT-2026-*"])
  status: InventoryCountSessionStatus | None = Field(None, description="Filter by session status.", examples=["planned"])
  type: InventoryCountSessionType | None = Field(None, description="Filter by counting dimension.", examples=["position"])
  limit: int | None = Field(500, description="Maximum number of results.", examples=[500])
  offset: int | None = Field(0, description="Pagination offset.", examples=[0])


class InventoryCountAssignmentNew(BaseModel):
  user_key: str = Field(..., description="Key of the user to assign this counting task to.", examples=["user/operator-01"])
  target_keys: list[str] = Field(..., description="List of position or product keys to assign, depending on the session type.", examples=[["12345", "67890"]])

class InventoryCountAssignment(ArangoDocument):
  inventory_count_session_key: str = Field(..., description="Key of the parent counting session.", examples=["cnt-session-001"])

  # What was assigned
  target_type: InventoryCountSessionType = Field(..., description="Whether this assignment targets a position or product.", examples=["position"])
  target_key: str = Field(..., description="Key of the target position or product.", examples=["12345"])

  # Assignment tracking
  assigned_to: str | None = Field(None, description="User key of the operator responsible for this assignment.", examples=["user/operator-01"])

  # Execution tracking
  status: InventoryCountAssignmentStatus | None = Field(InventoryCountAssignmentStatus.PLANNED, description="Current status of the assignment.", examples=["planned"])
  created: datetime = Field(default_factory=timestamp, description="Timestamp when the assignment was created.", examples=["2026-05-15T10:00:00Z"])
  created_by: str | None = Field(None, description="User key of the operator who created the assignment.", examples=["user/manager-01"])
  started: datetime | None = Field(None, description="Timestamp when the operator started counting.", examples=["2026-05-20T08:10:00Z"])
  completed: datetime | None = Field(None, description="Timestamp when the assignment was marked complete.", examples=["2026-05-20T09:30:00Z"])

  notes: str | None = Field(None, description="Free-text notes for this assignment.", examples=["Double-check rack 3"])
  extra: Any = Field(None, description="Arbitrary extra metadata.", examples=[None])


class InventoryCountAssignmentSearchParams(BaseModel):
  inventory_count_session_key: str | None = Field(None, description="Filter by parent session key.", examples=["cnt-session-001"])
  assignment_type: InventoryCountSessionType | None = Field(None, description="Filter by counting dimension.", examples=["position"])
  product_key: str | None = Field(None, description="Filter to assignments targeting this product key.", examples=["67890"])
  product_search: WildcardString = Field(None, description="Wildcard search on product code.", examples=["PROD-*"])
  position_key: str | None = Field(None, description="Filter to assignments targeting this position key.", examples=["12345"])
  position_search: WildcardString = Field(None, description="Wildcard search on position code.", examples=["LOCATION-A*"])
  assigned_to: str | None = Field(None, description="Filter by the user key the assignment is assigned to.", examples=["user/operator-01"])
  status: InventoryCountAssignmentStatus | None = Field(None, description="Filter by assignment status.", examples=["planned"])
  order_by: Literal['product', 'position'] | None = Field(None, description="Sort results by `product_key` or `position_key`.", examples=["position"])
  limit: int | None = Field(500, description="Maximum number of results.", examples=[500])
  offset: int | None = Field(0, description="Pagination offset.", examples=[0])

  def model_dump(self, *args, **kwargs):
    """Transforms category into record attribute name"""
    data = super().model_dump(*args, **kwargs)
    if self.order_by:
      data['order_by'] = f"{self.order_by}_key"
    return data


class InventoryCountStatus(str, Enum):
  STARTED = 'started'
  COMPLETED = 'completed'
  SUBMITTED = 'submitted'
  CONFIRMED = 'confirmed'
  DISCARDED = 'discarded'


class InventoryCountPositionCompleteRecord(ArangoDocument):  # edge collection: inventory_count_position_completed
  """Tracks whether all items in a position have been counted during a session."""
  session_id: str = Field(..., alias='_from', description="ArangoDB document ID of the counting session (`InventoryCountSession/<key>`).", examples=["InventoryCountSession/cnt-session-001"])
  position_id: str = Field(..., alias='_to', description="ArangoDB document ID of the counted position (`Position/<key>`).", examples=["Position/12345"])
  completed_at: datetime = Field(default_factory=timestamp, description="Timestamp when the position was marked as fully counted.", examples=["2026-05-20T09:30:00Z"])
  status: Literal['counted', 'empty'] = Field('counted', description="Outcome of the position count: `counted` means items were found; `empty` means the position was confirmed empty.", examples=["counted"])
  user_key: str | None = Field(None, description="User key of the operator who completed the position count.", examples=["user/operator-01"])
  notes: str | None = Field(None, description="Optional notes recorded when marking the position complete.", examples=["Rack 3 fully verified"])

class InventoryCountRecord(ArangoDocument): # edge collection inventory_count_record
  # What was counted
  product_id: str = Field(..., alias='_from', description="ArangoDB document ID of the product being counted (`Product/<key>`).", examples=["Product/67890"])
  position_id: str = Field(..., alias='_to', description="ArangoDB document ID of the position being counted (`Position/<key>`).", examples=["Position/12345"])

  # Core data - see validation below for ensuring correct setting
  system_qt: float = Field(..., description="System quantity snapshot taken at count start. Re-taken if the count record is updated before submission.", examples=[50.0])
  system_serial_keys: list[str] | None = Field(None, description="System serial keys snapshot at count start.", examples=[["SN-LR-001234"]])
  system_at: datetime | None = Field(default_factory=timestamp, description="Timestamp of the system quantity snapshot.", examples=["2026-05-20T08:00:00Z"])

  counted_qt: float | None = Field(None, description="Physical quantity found during count. Always set for non-started records.", examples=[48.0])
  counted_serial_keys: list[str] | None = Field(None, description="Serial keys physically found during count. If provided, must match `counted_qt`.", examples=[["SN-LR-001234"]])
  counted_at: datetime | None = Field(None, description="Timestamp when the physical count was recorded.", examples=["2026-05-20T09:15:00Z"])

  # Metadata
  inventory_count_session_key: str = Field(..., description="Key of the parent counting session.", examples=["cnt-session-001"])
  assignment_key: str | None = Field(None, description="Key of the assignment this record belongs to.", examples=["assign-001"])
  user_key: str | None = Field(None, description="User key of the operator who started the count.", examples=["user/operator-01"])
  status: InventoryCountStatus = Field(InventoryCountStatus.STARTED, description="Current status of the count record.", examples=["completed"])
  reviewed_at: datetime | None = Field(None, description="Timestamp when the record was confirmed or discarded during review.", examples=["2026-05-20T10:00:00Z"])
  processed: bool | None = Field(False, description="True when this record has been evaluated by `CountSessionAppliedEvent`.", examples=[False])
  movement_keys: list[str] | None = Field(None, description="Keys of adjustment movements generated when this record was applied.", examples=[["mvt-adj-001"]])
  notes: str | None = Field(None, description="Free-text notes from the counting operator.", examples=["Found 2 extra units on top shelf"])
  extra: Any = Field(None, description="Arbitrary extra metadata.", examples=[None])

  @property
  def product_key(self) -> str:
    return self.product_id.split('/')[-1]

  @property
  def position_key(self) -> str:
    return self.position_id.split('/')[-1]

  @property
  def delta(self) -> float | None:
    return self.counted_qt - self.system_qt

  @model_validator(mode='after')
  def handle_serials(self):
    # Ensure actual counts are recorded correctly
    if self.status != InventoryCountStatus.STARTED:
      if self.counted_serial_keys is not None and len(self.counted_serial_keys) > 0:
        serial_count = len(self.counted_serial_keys)
        if self.counted_qt is None:
          self.counted_qt = serial_count
        elif self.counted_qt != serial_count:
          raise ValueError(
            "serial qt must be equal to the number of serial_keys if provided: "
            f"Serial qt: {self.counted_qt}, serial_count: {serial_count}"
          )
      elif self.counted_qt is None:
        raise ValueError("You must provide either a counted quantity or a list of serial keys found")
    return self


class InventoryCountRecordSearchParams(BaseModel):
  count_session_key: str | None = Field(None, description="Filter by counting session key.", examples=["cnt-session-001"])
  user_key: str | None = Field(None, description="Filter by the user who created the count record.", examples=["user/operator-01"])
  assignment_key: str | None = Field(None, description="Filter by assignment key.", examples=["assign-001"])
  product_key: str | None = Field(None, description="Filter to count records for this product.", examples=["67890"])
  position_key: str | None = Field(None, description="Filter to count records for this position.", examples=["12345"])
  include_started: bool = Field(True, description="Include records in `started` status.", examples=[True])
  include_completed: bool = Field(True, description="Include records in `completed` status.", examples=[True])
  include_discarded: bool = Field(True, description="Include records in `discarded` status.", examples=[True])
  limit: int | None = Field(500, description="Maximum number of results.", examples=[500])
  offset: int | None = Field(0, description="Pagination offset.", examples=[0])

class InventorySnapshotSource(str, Enum):
  IMPORT = 'import'
  MRP = 'mrp'
  COUNT_SESSION = 'count_session'

class InventorySnapshotType(str, Enum):
  VIRTUAL = 'virtual'
  ACTUAL = 'actual'

class InventorySnapshotScopeType(str, Enum):
  FULL = 'full'
  POSITIONS = 'positions'
  PRODUCTS = 'products'

class InventorySnapshot(ArangoDocument):
  snapshot_type: InventorySnapshotType = Field(..., description="Whether this is a `virtual` (planned/projected) or `actual` (physical count) snapshot.", examples=["actual"])
  source: InventorySnapshotSource = Field(..., description="Source that generated this snapshot.", examples=["count_session"])
  inventory_count_session_key: str | None = Field(None, description="Key of the counting session that produced this snapshot (required when `source=count_session`).", examples=["cnt-session-001"])
  timestamp: datetime = Field(default_factory=timestamp, description="Timestamp when the snapshot was taken.", examples=["2026-05-20T08:00:00Z"])

  # Scope
  scope_type: InventorySnapshotScopeType = Field(InventorySnapshotScopeType.FULL, description="Coverage scope: `full` captures all inventory; `positions` or `products` scopes to a subset.", examples=["full"])
  target_keys: list[str] | None = Field(None, description="Keys of the positions or products in scope (used when `scope_type` is not `full`).", examples=[["12345", "67890"]])

  created_by: str | None = Field(None, description="User key of the operator who initiated the snapshot.", examples=["user/manager-01"])
  notes: str | None = Field(None, description="Free-text notes for the snapshot.", examples=["Pre-count baseline Q2 2026"])
  extra: Any = Field(None, description="Arbitrary extra metadata.", examples=[None])

  @model_validator(mode='after')
  def validate_session_relationship(self):
    # Session snapshots MUST have a session reference
    if self.source == InventorySnapshotSource.COUNT_SESSION and not self.inventory_count_session_key:
      raise ValueError("Count session snapshots must have a session reference")

    return self

class InventorySnapshotItem(ArangoDocument): # edge collection
  product_key: str = Field(..., alias='_from', description="ArangoDB document ID of the product (`Product/<key>`).", examples=["Product/67890"])
  position_key: str = Field(..., alias='_to', description="ArangoDB document ID of the position (`Position/<key>`).", examples=["Position/12345"])
  inventory_snapshot_key: str = Field(..., description="Key of the parent `InventorySnapshot`.", examples=["snap-001"])
  quantity: float = Field(..., description="Quantity of the product at this position at the time of the snapshot.", examples=[50.0])
  value: float | None = Field(None, description="Monetary value of this snapshot item.", examples=[1250.0])
  serial_keys: list[str] | None = Field(None, description="Serial keys at this position at the time of the snapshot.", examples=[["SN-LR-001234"]])
