from .admin import router as admin
from .auth import router as auth
from .bom import router as bom
from .file import router as file
from .form import router as form
from .org import router as org
from .print import router as print
from .process import router as process
from .product import router as product
from .production import router as production
from .quality import router as quality
from .traceability import router as traceability
