from .admin import router as admin
from .auth import router as auth
from .bom import router as bom
from .config import router as config
from .file import router as file
from .form import router as form
from .serialform import router as serialform
from .media import router as media
from .org import router as org
from .print import router as print
from .process import router as process
from .product import router as product
from .production import router as production
from .tag import router as tag
from .collaboration import router as collaboration
from .traceability import router as traceability
from .notification import router as notification
