[
{"namespace": "it.progresslab.services.avro",
 "type": "enum",
 "name": "SerialValidationType",
 "symbols" : ["INVENTORY_CHECK", "FRAUD_CHECK", "ORDER_DETAILS_CHECK"]
},
{"namespace": "it.progresslab.services.avro",
 "type": "enum",
 "name": "SerialValidationResult",
 "symbols" : ["PASS", "FAIL", "ERROR"]
},
{"namespace": "it.progresslab.services.avro",
 "type": "record",
 "name": "SerialValidation",
 "fields": [
     {"name": "serialId", "type": "string"},
     {"name": "checkType", "type": "SerialValidationType"},
     {"name": "validationResult",  "type": "SerialValidationResult"}
 ]
}]
