[
  {
    "namespace": "it.progresslab.services.avro",
    "type": "enum",
    "name": "SerialState",
    "symbols": [
      "CREATED",
      "VALIDATED",
      "FAILED",
      "SHIPPED"
    ]
  },
  {
    "namespace": "it.progresslab.services.avro",
    "type": "record",
    "name": "Serial",
    "fields": [
      {
        "name": "id",
        "type": "string"
      },
      {
        "name": "serialId",
        "type": "string"
      },
      {
        "name": "quantity",
        "type": "int"
      }
    ]
  },
  {
    "namespace": "it.progresslab.services.avro",
    "type": "record",
    "name": "SerialValue",
    "fields": [
      {
        "name": "serial",
        "type": "Serial"
      },
      {
        "name": "value",
        "type": "double"
      }
    ]
  }
]
